version: '3.8'
services:
  weather-backend:
    build: .
    environment:
      - PORT=5000
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - MONGO_URI=mongodb://mongo:27017/weatherdb
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
